name: build_docs
on: [push]

jobs:
  build-spinix:
    runs-on: windows-latest
    steps:
        - name: Check out repository code
          uses: actions/checkout@v2
        - name: setup python
          uses: actions/setup-python@v2
          with:
            python-version: 3.8 
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  
        - name: Building documentation
          run: |
            sphinx-build source public -b html
        - name: List files in the repository
          run: |
            ls ${{ github.workspace }}
        - run: echo " This job's status is ${{ job.status }}."
        - name: Depoly
          uses: JamesIves/github-pages-deploy-action@4.1.4
          with: 
            branch: gh-pages
            folder: public

