name: learn-github-actions
on: [push]
jobs:
  check-bulid-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: check batch bulid 
      - run: ..\make.bat
