name: build_docs
on: [push]

jobs:
  build-spinix:
    runs-on: windows-latest
    steps:
        - run: echo " The job was automatically triggered by a ${{ github.event_name }} event."
        - run: echo " This job is now running on a ${{ runner.os }} server hosted by GitHub!"
        - run: echo " The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
        - name: Check out repository code
          uses: actions/checkout@v2
        - name: setup python
          uses: actions/setup-python@v2
          with:
            python-version: 3.8 #install the python needed
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  
        - name: Building documentation
          run: |
            sphinx-build source public -b html
        - name: List files in the repository
          run: |
            ls ${{ github.workspace }}
        - run: echo " This job's status is ${{ job.status }}."
        - name: Depoly to gh-pages
          uses: JamesIves/github-pages-deploy-action@4.1.4
          with: 
            branch: gh-pages
            folder: public
        - uses: actions/setup-node@v2-beta
          with: 
            node-version: '12'
        - name: Install packages
          run: |
            npm install
        - name: Depoly to surge
          run: |
            npm install -g surge   
            surge ./public my-docs.surge.sh --token ${{secrets.TOKEN}}     

