name: learn-github-actions
on: [push]
jobs:
  check-bulid-html:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - run: echo "Hello World!"
